version: '3'

services:
  web:
    restart: "always"
    build:
      context: ./Services/django
      dockerfile: Dockerfile
    volumes:
      -  ./Services/django/:/usr/src/app/
      - static_volume:/usr/src/app/Services/django/static
    ports:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rocker
      - POSTGRES_PASSWORD=corona
      - POSTGRES_DB=FakeNews_db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/Services/django/static
      - media_volume:/usr/src/app/Services/django/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: