# Generated by Django 3.0.5 on 2020-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='got_acquisiton_product',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=50, null=True),
        ),
    ]
