# Generated by Django 3.0.5 on 2020-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_data', '0004_auto_20200422_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('hidden', 'Hidden')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('hidden', 'Hidden')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tags',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
